In [1]:
import pandas as pd 
import numpy as np

data = pd.read_csv('./data.csv',  index_col=None)


In [2]:
data

Unnamed: 0   Unnamed: 1          W1         W2        W3       W4  \
0          NaN      variant      1.0000    1.00000    1.0000   1.0000   
1          1.0      wild-Ca  -6427.9075  -82.88120  801.5275  42.1087   
2          2.0  wild-Nd/Ang  -8783.4075  113.85120  815.6950  40.4315   
3          3.0   wild-Nd/Li -10190.4975  211.07550  797.1550  40.8267   
4          4.0    D9A-Nd/Li -10006.6200  221.09000  799.1525  37.6500   
5          5.0   D9A-Nd/Ang  -8364.8200  121.33250  808.6175  39.6900   
6          6.0   D9H-Nd/Ang  -8555.1525  103.51035  831.6200  36.9790   
7          7.0    D9H-Nd/Li  -9955.3475  178.12800  843.9525  36.8072   
8          8.0   D9M-Nd/Ang  -8370.8500  113.48700  800.3425  39.2800   
9          9.0    D9M-Nd/Li  -9660.9450  157.55010  798.4400  39.4845   
10        10.0   D9N-Nd/Ang  -8475.0350  115.78800  725.9150  40.3900   
11        11.0    D9N-Nd/LI  -9809.4650  164.27420  732.1500  40.4640   

       Sum_E_W  sum_E_norm_W  Expt. Kd   Kd_norm  difference  
0          NaN           NaN       NaN       NaN         NaN  
1  -5667.15250      0.619941       7.1  0.001744    0.618196  
2  -7813.42980      0.854726    4070.0  1.000000    0.145274  
3  -9141.44030      1.000000    4070.0  1.000000    0.000000  
4  -8948.72750      0.978919     397.0  0.097543    0.881376  
5  -7395.18000      0.808973     397.0  0.097543    0.711430  
6  -7583.04315      0.829524    2150.0  0.528256    0.301268  
7  -8896.45980      0.973201    2150.0  0.528256    0.444946  
8  -7417.74050      0.811441    1460.0  0.358722    0.452719  
9  -8665.47040      0.947933    1460.0  0.358722    0.589210  
10 -7592.94200      0.830607      53.1  0.013047    0.817560  
11 -8872.57680      0.970588      53.1  0.013047    0.957542

In [36]:
kd_norm = list(data['Kd_norm'][1:])


kd_file = []
for i in kd_norm:
    rank = []
    for j in kd_norm:
        rank.append(i-j)
    kd_file.append(rank)
pd.DataFrame(np.array(kd_file)/np.max(np.array(kd_file)))

0         1         2         3         4         5         6   \
0   0.000000 -1.000000 -1.000000 -0.095966 -0.095966 -0.527431 -0.527431   
1   1.000000  0.000000  0.000000  0.904034  0.904034  0.472569  0.472569   
2   1.000000  0.000000  0.000000  0.904034  0.904034  0.472569  0.472569   
3   0.095966 -0.904034 -0.904034  0.000000  0.000000 -0.431465 -0.431465   
4   0.095966 -0.904034 -0.904034  0.000000  0.000000 -0.431465 -0.431465   
5   0.527431 -0.472569 -0.472569  0.431465  0.431465  0.000000  0.000000   
6   0.527431 -0.472569 -0.472569  0.431465  0.431465  0.000000  0.000000   
7   0.357602 -0.642398 -0.642398  0.261636  0.261636 -0.169829 -0.169829   
8   0.357602 -0.642398 -0.642398  0.261636  0.261636 -0.169829 -0.169829   
9   0.011322 -0.988678 -0.988678 -0.084644 -0.084644 -0.516109 -0.516109   
10  0.011322 -0.988678 -0.988678 -0.084644 -0.084644 -0.516109 -0.516109   

          7         8         9         10  
0  -0.357602 -0.357602 -0.011322 -0.011322  
1   0.642398  0.642398  0.988678  0.988678  
2   0.642398  0.642398  0.988678  0.988678  
3  -0.261636 -0.261636  0.084644  0.084644  
4  -0.261636 -0.261636  0.084644  0.084644  
5   0.169829  0.169829  0.516109  0.516109  
6   0.169829  0.169829  0.516109  0.516109  
7   0.000000  0.000000  0.346280  0.346280  
8   0.000000  0.000000  0.346280  0.346280  
9  -0.346280 -0.346280  0.000000  0.000000  
10 -0.346280 -0.346280  0.000000  0.000000

In [37]:
pd.DataFrame(kd_file)

0         1         2         3         4         5         6   \
0   0.000000 -0.998256 -0.998256 -0.095799 -0.095799 -0.526511 -0.526511   
1   0.998256  0.000000  0.000000  0.902457  0.902457  0.471744  0.471744   
2   0.998256  0.000000  0.000000  0.902457  0.902457  0.471744  0.471744   
3   0.095799 -0.902457 -0.902457  0.000000  0.000000 -0.430713 -0.430713   
4   0.095799 -0.902457 -0.902457  0.000000  0.000000 -0.430713 -0.430713   
5   0.526511 -0.471744 -0.471744  0.430713  0.430713  0.000000  0.000000   
6   0.526511 -0.471744 -0.471744  0.430713  0.430713  0.000000  0.000000   
7   0.356978 -0.641278 -0.641278  0.261179  0.261179 -0.169533 -0.169533   
8   0.356978 -0.641278 -0.641278  0.261179  0.261179 -0.169533 -0.169533   
9   0.011302 -0.986953 -0.986953 -0.084496 -0.084496 -0.515209 -0.515209   
10  0.011302 -0.986953 -0.986953 -0.084496 -0.084496 -0.515209 -0.515209   

          7         8         9         10  
0  -0.356978 -0.356978 -0.011302 -0.011302  
1   0.641278  0.641278  0.986953  0.986953  
2   0.641278  0.641278  0.986953  0.986953  
3  -0.261179 -0.261179  0.084496  0.084496  
4  -0.261179 -0.261179  0.084496  0.084496  
5   0.169533  0.169533  0.515209  0.515209  
6   0.169533  0.169533  0.515209  0.515209  
7   0.000000  0.000000  0.345676  0.345676  
8   0.000000  0.000000  0.345676  0.345676  
9  -0.345676 -0.345676  0.000000  0.000000  
10 -0.345676 -0.345676  0.000000  0.000000

In [4]:
weights = np.array([1,1,1,1])
data_4 = np.array(data[["W1","W2","W3","W4"]][1:12])
data_4

array([[ -6427.9075 ,    -82.8812 ,    801.5275 ,     42.1087 ],
       [ -8783.4075 ,    113.8512 ,    815.695  ,     40.4315 ],
       [-10190.4975 ,    211.0755 ,    797.155  ,     40.8267 ],
       [-10006.62   ,    221.09   ,    799.1525 ,     37.65   ],
       [ -8364.82   ,    121.3325 ,    808.6175 ,     39.69   ],
       [ -8555.1525 ,    103.51035,    831.62   ,     36.979  ],
       [ -9955.3475 ,    178.128  ,    843.9525 ,     36.8072 ],
       [ -8370.85   ,    113.487  ,    800.3425 ,     39.28   ],
       [ -9660.945  ,    157.5501 ,    798.44   ,     39.4845 ],
       [ -8475.035  ,    115.788  ,    725.915  ,     40.39   ],
       [ -9809.465  ,    164.2742 ,    732.15   ,     40.464  ]])

In [38]:
list_ = []
for i in range(data_4.shape[0]):
    list_.append(np.sum(data_4[i]*weights))
list_ = np.array(list_/min(list_))


file = []
for i in list_:
    rank = []
    for j in list_:
        rank.append((i-j))
    file.append(rank)

np_eW = np.array(file)/np.max(np.array(file))
pd.DataFrame(np_eW)

0         1         2         3         4         5         6   \
0   0.000000 -0.617760 -1.000000 -0.944532 -0.497376 -0.551448 -0.929488   
1   0.617760  0.000000 -0.382240 -0.326771  0.120384  0.066312 -0.311727   
2   1.000000  0.382240  0.000000  0.055468  0.502624  0.448552  0.070512   
3   0.944532  0.326771 -0.055468  0.000000  0.447156  0.393083  0.015044   
4   0.497376 -0.120384 -0.502624 -0.447156  0.000000 -0.054072 -0.432112   
5   0.551448 -0.066312 -0.448552 -0.393083  0.054072  0.000000 -0.378039   
6   0.929488  0.311727 -0.070512 -0.015044  0.432112  0.378039  0.000000   
7   0.503870 -0.113891 -0.496130 -0.440662  0.006494 -0.047579 -0.425618   
8   0.863002  0.245242 -0.136998 -0.081530  0.365626  0.311554 -0.066485   
9   0.554298 -0.063463 -0.445702 -0.390234  0.056922  0.002849 -0.375190   
10  0.922613  0.304853 -0.077387 -0.021918  0.425237  0.371165 -0.006874   

          7         8         9         10  
0  -0.503870 -0.863002 -0.554298 -0.922613  
1   0.113891 -0.245242  0.063463 -0.304853  
2   0.496130  0.136998  0.445702  0.077387  
3   0.440662  0.081530  0.390234  0.021918  
4  -0.006494 -0.365626 -0.056922 -0.425237  
5   0.047579 -0.311554 -0.002849 -0.371165  
6   0.425618  0.066485  0.375190  0.006874  
7   0.000000 -0.359133 -0.050428 -0.418744  
8   0.359133  0.000000  0.308705 -0.059611  
9   0.050428 -0.308705  0.000000 -0.368316  
10  0.418744  0.059611  0.368316  0.000000

In [39]:
np_kd = np.array(kd_file)/np.max(np.array(kd_file))
pd.DataFrame(np_kd)

0         1         2         3         4         5         6   \
0   0.000000 -1.000000 -1.000000 -0.095966 -0.095966 -0.527431 -0.527431   
1   1.000000  0.000000  0.000000  0.904034  0.904034  0.472569  0.472569   
2   1.000000  0.000000  0.000000  0.904034  0.904034  0.472569  0.472569   
3   0.095966 -0.904034 -0.904034  0.000000  0.000000 -0.431465 -0.431465   
4   0.095966 -0.904034 -0.904034  0.000000  0.000000 -0.431465 -0.431465   
5   0.527431 -0.472569 -0.472569  0.431465  0.431465  0.000000  0.000000   
6   0.527431 -0.472569 -0.472569  0.431465  0.431465  0.000000  0.000000   
7   0.357602 -0.642398 -0.642398  0.261636  0.261636 -0.169829 -0.169829   
8   0.357602 -0.642398 -0.642398  0.261636  0.261636 -0.169829 -0.169829   
9   0.011322 -0.988678 -0.988678 -0.084644 -0.084644 -0.516109 -0.516109   
10  0.011322 -0.988678 -0.988678 -0.084644 -0.084644 -0.516109 -0.516109   

          7         8         9         10  
0  -0.357602 -0.357602 -0.011322 -0.011322  
1   0.642398  0.642398  0.988678  0.988678  
2   0.642398  0.642398  0.988678  0.988678  
3  -0.261636 -0.261636  0.084644  0.084644  
4  -0.261636 -0.261636  0.084644  0.084644  
5   0.169829  0.169829  0.516109  0.516109  
6   0.169829  0.169829  0.516109  0.516109  
7   0.000000  0.000000  0.346280  0.346280  
8   0.000000  0.000000  0.346280  0.346280  
9  -0.346280 -0.346280  0.000000  0.000000  
10 -0.346280 -0.346280  0.000000  0.000000

In [40]:
pd.DataFrame(abs(np_kd-np_eW))

0         1         2         3         4         5         6   \
0   0.000000  0.382240  0.000000  0.848566  0.401410  0.024017  0.402056   
1   0.382240  0.000000  0.382240  1.230805  0.783650  0.406257  0.784296   
2   0.000000  0.382240  0.000000  0.848566  0.401410  0.024017  0.402056   
3   0.848566  1.230805  0.848566  0.000000  0.447156  0.824548  0.446509   
4   0.401410  0.783650  0.401410  0.447156  0.000000  0.377393  0.000646   
5   0.024017  0.406257  0.024017  0.824548  0.377393  0.000000  0.378039   
6   0.402056  0.784296  0.402056  0.446509  0.000646  0.378039  0.000000   
7   0.146268  0.528508  0.146268  0.702298  0.255142  0.122251  0.255789   
8   0.505400  0.887640  0.505400  0.343165  0.103990  0.481383  0.103344   
9   0.542976  0.925215  0.542976  0.305590  0.141566  0.518958  0.140919   
10  0.911291  1.293531  0.911291  0.062726  0.509881  0.887274  0.509235   

          7         8         9         10  
0   0.146268  0.505400  0.542976  0.911291  
1   0.528508  0.887640  0.925215  1.293531  
2   0.146268  0.505400  0.542976  0.911291  
3   0.702298  0.343165  0.305590  0.062726  
4   0.255142  0.103990  0.141566  0.509881  
5   0.122251  0.481383  0.518958  0.887274  
6   0.255789  0.103344  0.140919  0.509235  
7   0.000000  0.359133  0.396708  0.765024  
8   0.359133  0.000000  0.037575  0.405891  
9   0.396708  0.037575  0.000000  0.368316  
10  0.765024  0.405891  0.368316  0.000000

In [41]:
np.sum(abs(np_kd-np_eW))

50.83760012076861

In [42]:
def sum_calc(weights, kd_file, data_4):
    list_ = []
    for i in range(data_4.shape[0]):
        list_.append(np.sum(data_4[i]*weights))

    list_ = np.array(list_/min(list_))

    file = []
    for i in list_:
        rank = []
        for j in list_:
            rank.append((i-j))
        file.append(rank)

    # pd.DataFrame(abs(np.array(file) - np.array(kd_file)))
    np_kd = np.array(kd_file)/np.max(np.array(kd_file))
    np_eW = np.array(file)/np.max(np.array(file))
    return np.sum(abs(np_kd-np_eW))

In [43]:
sum_calc(weights, kd_file, data_4)

50.83760012076861

In [44]:
frac = np.linspace(.1,1,10)
mult = np.linspace(2,10,9)
frac_mult = np.concatenate((frac,mult), axis = 0)
frac_mult

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  2. ,
        3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ])

In [45]:
dict_ = {}
counter = 0
for i in frac_mult:
    for j in frac_mult:
        for k in frac_mult:
            for l in frac_mult:
                inside_dict = {}
                inside_dict['w1'] = i
                inside_dict['w2'] = j
                inside_dict['w3'] = k
                inside_dict['w4'] = l 
                
                sum_ = sum_calc(np.array([i,j,k,l]), kd_file, data_4)
                inside_dict['sum'] = sum_
                dict_[counter] = inside_dict
                counter+=1

In [46]:
main_data = pd.DataFrame(dict_).transpose().sort_values(by = 'sum')

In [47]:
main_data

w1   w2    w3    w4        sum
4312   0.1  3.0   9.0  10.0  40.943174
4293   0.1  3.0   8.0  10.0  40.966190
4692   0.1  4.0  10.0  10.0  40.981452
4311   0.1  3.0   9.0   9.0  41.012233
4691   0.1  4.0  10.0   9.0  41.041692
...    ...  ...   ...   ...        ...
33444  0.5  8.0   4.0   0.5  74.710509
33443  0.5  8.0   4.0   0.4  74.711768
33442  0.5  8.0   4.0   0.3  74.713026
33441  0.5  8.0   4.0   0.2  74.714283
33440  0.5  8.0   4.0   0.1  74.715539

[130321 rows x 5 columns]

In [67]:
w_1 = np.linspace(.00001,.001,10)
w_2 = np.linspace(1.8,3.2,20)
w_3 = np.linspace(5,15,20)
w_4 = np.linspace(60,120,20)


In [56]:
w_2

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [68]:
dict_ = {}
counter = 0
for i in w_1:
    for j in w_2:
        for k in w_3:
            for l in w_4:
                inside_dict = {}
                inside_dict['w1'] = i
                inside_dict['w2'] = j
                inside_dict['w3'] = k
                inside_dict['w4'] = l 
                
                sum_ = sum_calc(np.array([i,j,k,l]), kd_file, data_4)
                inside_dict['sum'] = sum_
                dict_[counter] = inside_dict
                counter+=1

In [69]:
main_data = pd.DataFrame(dict_).transpose().sort_values(by = 'sum')
main_data

w1        w2         w3         w4        sum
66052  0.00089  2.168421   6.052632  97.894737  31.182868
58052  0.00078  2.168421   6.052632  97.894737  31.183366
74052  0.00100  2.168421   6.052632  97.894737  31.183648
50052  0.00067  2.168421   6.052632  97.894737  31.183864
42052  0.00056  2.168421   6.052632  97.894737  31.184361
...        ...       ...        ...        ...        ...
40380  0.00056  1.800000  15.000000  60.000000  39.338729
48380  0.00067  1.800000  15.000000  60.000000  39.342105
56380  0.00078  1.800000  15.000000  60.000000  39.345481
64380  0.00089  1.800000  15.000000  60.000000  39.348858
72380  0.00100  1.800000  15.000000  60.000000  39.352235

[80000 rows x 5 columns]